### ISSUE TITLE
Make font-size and font-weight easily customizable

### ISSUE THREAD

**Issue by bertysentry** [sentrysoftware/sentry-maven-skin#97]
# Enhancement

Users can specify the font family value in variables:

```css
body.my-theme {
  --title-heavy-font: "Gill Sans", sans-serif;
  --title-font: system-ui;
  --content-font: Georgia, serif;
}
```

but users may need to adjust `font-size`, `font-weight`, and maybe `font-style` as well.

# Specification

* Update `sentry.css` to use variables for `font-size`, `font-weight`, and `font-style`.
* Document the use of these CSS variables in `styling.md`
